apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: demo

spec:
  ingressClassName: traefik
  rules:
    - host: api.elpsykongroo.com
      http:
        paths:
          - path: /public
            pathType: Exact
            backend:
              service:
                name:  demo
                port:
                  number: 443
        