{{- if .Values.service.headless.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}-headless
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.headless.port }}
      targetPort: {{ .Values.service.headless.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
{{- end}}